### ISSUE TITLE
Unable to upgrade to 1.1.22 via apt - broken openSUSE mirror?

### ISSUE THREAD

**Issue by rabyj** [doublecmd/doublecmd#2113]
### Version

Double Commander
Version: 1.1.21 gamma
Revision: 630
Commit: 9c148b222
Build date: 2024/11/30
Lazarus: 2.2.6.0
FPC: 3.2.2
Platform: x86_64-Linux-gtk2
OS version: Ubuntu 20.04.6 LTS

Widgetset library: GTK 2.24.32

### Description

Trying to upgrade from 1.1.21 to 1.1.22 via apt. It's failing because a "File has unexpected size (992076 != 2738840)"

The first time I installed the program, I followed the openSUSE build service instructions ([here](https://software.opensuse.org/download.html?project=home%3AAlexx2000&package=doublecmd-gtk))

Is the mirror not properly synced, like `apt` says, or is it something else? The [last sync](https://download.opensuse.org/download/repositories/home:/Alexx2000/xUbuntu_20.04/?status=recent) seems to indicate at least 3 files are missing, but I'm not familiar with this build service so maybe that's not meaningful.

Is this normal and I just have to wait a few more days?

Thanks for any info!

---
Following are the `apt` outputs, and my system specs.

**apt update**
`Get:18 http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04  InRelease [1,543 B]`

**apt upgrade**
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  mongodb-org mongodb-org-mongos mongodb-org-server mongodb-org-shell mongodb-org-tools
The following packages will be upgraded:
  doublecmd-common doublecmd-gtk doublecmd-plugins
3 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Need to get 8,729 kB of archives.
After this operation, 36.9 kB of additional disk space will be used.
Get:1 http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04  doublecmd-gtk 1.1.22-0+svn661~testing [4,998 kB]
Get:2 http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04  doublecmd-plugins 1.1.22-0+svn661~testing [992 kB]
Get:3 http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04  doublecmd-common 1.1.22-0+svn661~testing [2,739 kB]
Err:3 http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04  doublecmd-common 1.1.22-0+svn661~testing
  File has unexpected size (992076 != 2738840). Mirror sync in progress? [IP: 10.44.82.81 9999]
  Hashes of expected file:
   - SHA256:ff60a3ebf9f46417d5138bca8b5edddc40013b054f6c87b6aed2acb931814182
   - SHA1:6534b43c0490c9d914af86c0dcc17e96b012d5f4 [weak]
   - MD5Sum:9c439cf466d0ea4721d395457c49a0c2 [weak]
   - Filesize:2738840 [weak]
Fetched 5,990 kB in 1s (11.1 MB/s)
E: Failed to fetch http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04/all/doublecmd-common_1.1.22-0+svn661~testing_all.deb  File has unexpected size (992076 != 2738840). Mirror sync in progress? [IP: 10.44.82.81 9999]
   Hashes of expected file:
    - SHA256:ff60a3ebf9f46417d5138bca8b5edddc40013b054f6c87b6aed2acb931814182
    - SHA1:6534b43c0490c9d914af86c0dcc17e96b012d5f4 [weak]
    - MD5Sum:9c439cf466d0ea4721d395457c49a0c2 [weak]
    - Filesize:2738840 [weak]
E: Unable to fetch some archives, try running apt-get update or apt-get --fix-missing.
```

**Comment by alexx2000** [comment]
Should work now. Execute `apt update` and `apt upgrade` again.

**Comment by rabyj** [comment]
Thanks for the quick answer, but sadly I got the same error.

I removed `doublecmd-gtk` and did `autoremove` which removed `doublecmd-common` and doublecmd-plugins`.

Reinstalling does not work (even after `apt clean`):
```
user@pc:~$ sudo apt install doublecmd-gtk -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  doublecmd-common doublecmd-plugins
Suggested packages:
  doublecmd-help-en | doublecmd-help libffmpegthumbnailer4v5 libunrar5 mplayer rabbitvcs-core
The following NEW packages will be installed:
  doublecmd-common doublecmd-gtk doublecmd-plugins
0 upgraded, 3 newly installed, 0 to remove and 5 not upgraded.
Need to get 2,739 kB/8,729 kB of archives.
After this operation, 43.8 MB of additional disk space will be used.
Get:1 http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04  doublecmd-common 1.1.22-0+svn662~testing [2,739 kB]
Err:1 http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04  doublecmd-common 1.1.22-0+svn662~testing
  File has unexpected size (992720 != 2738868). Mirror sync in progress? [IP: 10.44.82.81 9999]
  Hashes of expected file:
   - SHA256:76b1f1800acb6e5204a80e890d24011602a4aefb2c29044e1a990f123341243f
   - SHA1:59fa8de91b95ad554e49c3e46170db314bbe972e [weak]
   - MD5Sum:e08e510d38247d4243cd69c7f1397fbc [weak]
   - Filesize:2738868 [weak]
E: Failed to fetch http://download.opensuse.org/repositories/home:/Alexx2000/xUbuntu_20.04/all/doublecmd-common_1.1.22-0+svn662~testing_all.deb  File has unexpected size (992720 != 2738868). Mirror sync in progress? [IP: 10.44.82.81 9999]
   Hashes of expected file:
    - SHA256:76b1f1800acb6e5204a80e890d24011602a4aefb2c29044e1a990f123341243f
    - SHA1:59fa8de91b95ad554e49c3e46170db314bbe972e [weak]
    - MD5Sum:e08e510d38247d4243cd69c7f1397fbc [weak]
    - Filesize:2738868 [weak]
E: Unable to fetch some archives, try running apt-get update or apt-get --fix-missing.
```

**Comment by alexx2000** [comment]
I recreated a repository. Try to re-add it:
```
curl -fsSL https://download.opensuse.org/repositories/home:Alexx2000/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_Alexx2000.gpg > /dev/null
sudo apt update
sudo apt install doublecmd-gtk
```

**Comment by rabyj** [comment]
I SOLVED IT!

I got the same problem again just re-adding the released key, so I tried to start from a clean slate.

There must have been a backup file somewhere creating a problem, I manually deleted the PPA and keys and THEN re-added, and then it installed properly. Thanks for trying on your end too, sorry for the trouble!

For reference, to remove I did
`sudo rm /etc/apt/sources.list.d/home:Alexx2000*`
`sudo rm /etc/apt/trusted.gpg.d/home_Alexx2000.gpg*`

**Comment by janos-r** [comment]
I tried the same but it didn't work!
I deleted both files as described, added them back via instructions in 
https://software.opensuse.org/download.html?project=home%3AAlexx2000&package=doublecmd-gtk
I did `sudo apt update` between both steps, but the `sudo apt install doublecmd-gtk` still throws the same error about unexpected size!
Please let me know if you know how to solve this. I have to disable this repo for the first time to not block my normal updates!

**Comment by rabyj** [comment]
@janos-r Just to make sure I understand correctly, you
- Removed the source.list file, the key file, and any of their backups, as instructed above.
- Ran `sudo apt clean`
- Added the repo back, running the commands given (What is your system+version, what exactly did you run?)

After all that, `sudo apt update` gave the unexpected size error? 

Maybe the author can help with more details, but I'm stumped.

**Comment by janos-r** [comment]
Thanks for the tip. `sudo apt clean` did really solve it.
I didn't even need to re-add the repo and key files. I never used the clean command before, now I understand that apt complained about a different upstream archive compared to something in a local cache I assume.

**Comment by rabyj** [comment]
yaye! You're welcome =^.^=
