### ISSUE TITLE
Mouse drag n drop: move instead of  copy

### ISSUE THREAD

**Issue by Pareidol** [doublecmd/doublecmd#271]
From most other filecommanders I'm used to move with mouse drag n drop instead of copy files/folders.
An option to change the behaviour would be handy.

**Comment by antodc** [comment]
Holding the shift button while dragging should do the job.

**Comment by WhiteChairFromIkea** [comment]
There is an option in freecommander: "Always ask drop action for drag and drop operation", which throws nag submenu with offerings what to do on mouse button release, it is pretty convenient, it is always clear what is going to happen (copy or move), but requires additional mouse click on every drag and drop operation:      
![41223](https://user-images.githubusercontent.com/46539653/143018435-c2735825-8b68-44fb-afd9-a07a6c278eb7.png)

**Comment by Pareidol** [comment]
I, know but it's not intuitive, when you are "trained" by other explorers,
and this is something that often leads me back to other explorers. I think
it's easy for you to add as option but it's something that could lead more
people to try out double commander as explorer. I think, make the
transition as easy as possible for new users. Forcing new workflows is
never a good idea.


- - - - - - - - - - - - - - - - - - - - - - - - - - - -
Mit freundlichen Grüßen

Marco Bimbös
Felsenstraße 84
70794 Filderstadt

☎ +49174 / 2146601

antodc ***@***.***> schrieb am Di., 23. Nov. 2021, 12:35:

**Comment by j2969719** [comment]
dc shows drop action menu if drag n drop is performed with right mouse button

**Comment by Pareidol** [comment]
I know. I know the right click, the shift, the buttons in the tool bar, I
know that I can assign shortcuts... But that's all a different workflow
from what I (and many others regarding forum and reddit posts) are used to
have in our muscle memory. And additional, for me it makes no sense. I
definitely do more often move files instead of copy. And it should be
possible to perform the "standard" action without the need of additional
buttons.
I assume such an option is no big deal (compared to the other more complex
options that are not so important in my eyes). I would appreciate to see
this option, and I bet many other's will do too.


- - - - - - - - - - - - - - - - - - - - - - - - - - - -
Mit freundlichen Grüßen

Marco Bimbös
Felsenstraße 84
70794 Filderstadt

☎ +49174 / 2146601

j2969719 ***@***.***> schrieb am Di., 23. Nov. 2021, 14:14:

**Comment by hgdrn** [comment]
When speaking of Dragging & Dropping files:
The default operation in Total Commander is Copy.
The default operation in Double Commander is Copy.
The default operation in Krusader is Copy.

I guess it's the same in Gnome Commander and any other Norton Commander clone.

I don't see any problem here.

**Comment by j2969719** [comment]
>But that's all a different workflow

exactly

dc - [ofm](https://en.wikipedia.org/wiki/File_manager#Orthodox_file_managers) 
while explorer & co - [navigational file manager](https://en.wikipedia.org/wiki/File_manager#Navigational_file_managers)

**Comment by Pareidol** [comment]
You are right, those explorers implemented it in the same way, and there is
the same discussion from users in their forum and on reddit as well.
There is a saying that goes "just dead fish swim with the stream". That
they implemented it in that way, doesn't mean it's the right solution.
The question wasn't to change the standard behaviour, the question was for
a tickbox to swap between move and copy. And I bet, in all the time we
discussed now about that option, it would have been implemented.
For your information: There are many expolrers that have it implemented the
other way arround, than your suggested ones:
- Windows explorer
- Mac Finder
- FreeCommander
- Multicommander


Am Di., 23. Nov. 2021 um 16:05 Uhr schrieb j2969719 <
***@***.***>:

**Comment by j2969719** [comment]
i think that most users choose ofm not cause its the "right solution", but because they are "implemented in this way". its just a niche type of software.

drag n drop behavior is not the only thing that differs from navigation fms. _in my opinion_, in case of a project with one active developer, an attempt to create some kind of optional hybrid somewhere in the middle can only slow down development of essential ofm functionality

**Comment by hgdrn** [comment]
> The question wasn't to change the standard behaviour, the question was for a tickbox to swap between move and copy.

Shouldn't be a big thing, that's true.

**Comment by rabyj** [comment]
so was this tickbox ever implemented? otherwise what's the name of the drag&copy main action in the settings, so we can change it/swap it? Shortcuts don't seem to include that action.

**Comment by vertigo220** [comment]
I have to say, I've tried XYplorer (my favorite, but crashes a LOT) and DOpus (also really good, though I hesitate to buy yet another FM for Windows when I'm planning on switching to linux within the next year) as well as several others, and DC seemed very promising. It's small, fast, stable, and mostly well-designed with a fair amount of features, and since it's cross-platform, I was really hoping I'd found one to replace all the others and to use in Windows and, eventually, linux, and so I spent quite a bit of time configuring everything and trying it out last night. But while there are numerous small things I've found about it that could, IMO, use some improvement, there are a few behavioral things that make it absolutely unusable for me, and this is one of them. And seeing as this issue has been open for 3 years without any indication it will be changed, it not only leaves me unable to switch to it, but with little hope that it will ever be usable for me.

I realize more options mean more coding and more maintenance, but it's a shame such a basic behavior, which goes against not only what many are used to but what is most efficient in a typical workflow, isn't being given an option to modify it.

**Comment by alexx2000** [comment]
I will add an option.

**Comment by alexx2000** [comment]
Done, option `DefaultDropEffect` in the `doublecmd.xml`, `True - Copy, False - Move`.

**Comment by vertigo220** [comment]
@alexx2000 Thanks for adding this, but I just installed the latest version where it was added, but nothing comes up when searching for that option. Is it something we have to add? If so, where/how? It would be ideal to have it as a checkbox option on the Mouse Drag & Drop settings page, as this would make it both easier to change and more obvious that it's even an option (especially with the option's name and "True/False" values instead of "Copy/Move") but at the very least I thought it would be as simple as searching the xml for "defaultdrop" and replacing "False" with "True."

**Comment by JonnyTech** [comment]
As Alexx stated above, you must manually edit the config file `doublecmd.xml`

Set `DefaultDropEffect` to `True` for **Copy**, and `False` for **Move**.

**Comment by vertigo220** [comment]
Ok, well, searching for that string with DC's own editor didn't find it, so I didn't know where to put it. Searching with a different editor found it. So just tried again with DC's editor and it was there. Only thing I can figure is it wasn't there when I first installed and launched DC and then was added after I closed and relaunched it.

**Comment by vertigo220** [comment]
Got it working, though, while a good start, it still doesn't behave as expected. I, and I suspect most others wanting this, only want it to move when dragging from one folder to another on the same drive, and copy while dragging to a folder on a different drive. Any chance of a secondary option to modify the behavior in this way? Could be either DefaultDropEffectSame and DefaultDropEffectDifferent or an option along the lines of InvertDropEffectDifferent.

**Comment by alexx2000** [comment]
This behavior is extremely illogical, I never understood it. It is harder to implement it. I don't plan to implement it at this moment.

**Comment by vertigo220** [comment]
That's fair. It makes sense and seems logical to me because of years/decades of operating with this behavior, and most FMs I've used do this, as well as copy handler programs. I'm assuming you come from a linux or macOS background and so this would seem strange to you. My feeling is, the more users can at least optionally get functionality in line with what they're used to in linux, the easier it will be for them to make the switch. And with W11, I know many people, myself included, are looking very seriously at doing so in the next year or two. Seeing as DC is cross-platform and is, AFAICT, one of the most if not _the_ most feature-filled FM for linux, it seems like a great option for users once they make the transition, but also in preparing for it. So giving it the ability to at least optionally behave in the same way would be beneficial.

And while I admit I don't really know what it would involve, it doesn't seem it would be that difficult to have it know whether a drag-and-drop is being done from/to the same drive or different drives, and then choose which action to perform based on that. That said, if #1898 is addressed, that would go a long way toward dealing with this issue as well as improving general usability and interoperability.

**Comment by danpeig** [comment]
This is an excellent feature/setting! I just suggest it is better documented or displayed in the configuration GUI because I found this discussion by accident and perhaps in the future no one will know about it.

**Comment by wk34u** [comment]
> Done, option `DefaultDropEffect` in the `doublecmd.xml`, `True - Copy`, `False - Move`.

I couldn’t find any configuration option in the interface. Fortunately, I found this issue—thanks for documenting it here.

**Comment by CrispyDrone** [comment]
Doublecmd seems to simply overwrite the file when I change the setting from `True` to `False`. I restart the application and it changes back to `True`.

I'm using version 1.1.32 gamma Revision 830 commit 187d1473a

**Comment by alexx2000** [comment]
Read [WARNING](https://doublecmd.github.io/doc/en/configxml.html#manualed).
