### ISSUE TITLE
some dialog buttons are not painted until dialog is moved / resized

### ISSUE THREAD

**Issue by Kolcha** [doublecmd/doublecmd#378]
Double Commander
Version: 1.0.4 beta
Revision: 84
Commit: a1d58d4dd
Build date: 2022/02/13
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: Debian bookworm/sid

Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1

some buttons on delete/copy/move dialogs don't appear until dialog is moved or resized. see attached screenshots for details. it is enough just to slightly move the dialog to make missing buttons appear (see screenshot with copy dialog). but even with invisible buttons desired action is happen (at least pressing "Enter" produces expected result).
Double Commander is used in GTK-based environment, for now it's XFCE, previously bug was observed in MATE, even earlier (few years ago) - in GNOME 3. X11 is used as graphics "engine", nothing Wayland-based is running on my system.
everything is installed from official Debian Unstable repos. no any custom repos are added to system.

this issue I observed long time ago, but decided to report only now, because for now it became important to me to switch to Qt5-based interface from GTK2-based I used for a long time due to 10-bit screen output support (GTK2 interface has few ugly and annoying bugs, which are very likely library limitations, but Qt-based interface looks fine). also I have HighDPI screen (already about 10 years) and Qt deals with it much better, especially nowadays.

bug is definitely not distro-specific, I saw it at least on Fedora, Ubuntu, Arch and Debian. but this is may be related to HighDPI, right now I have some settings (like custom dpi = 144) for that.

used Qt style (I'm using default Qt built-in style called "Fusion") doesn't affect this bug in any way, qt5ct settings are also have no effect on this.

![Screenshot_2022-03-21_00-14-18](https://user-images.githubusercontent.com/947647/159186903-647bcb6a-be6e-4e63-8426-59c772b3b825.png)

![Screenshot_2022-03-21_00-14-48](https://user-images.githubusercontent.com/947647/159186905-5b36325c-06ad-4744-bff9-e33270fa01bf.png)
![Screenshot_2022-03-21_00-15-16](https://user-images.githubusercontent.com/947647/159186907-03c039b4-0a20-4cc4-ac3d-7e70c15f552d.png)

![Screenshot_2022-03-21_00-15-39](https://user-images.githubusercontent.com/947647/159186910-83883680-0fa8-48ea-bee7-44c73fbdc865.png)

**Comment by Skif-off** [comment]
Looks like [issue 261](https://github.com/doublecmd/doublecmd/issues/261), but should have been fixed in 1.0.2 or 1.0.3. Can you try the latest alpha? AppImage [here](https://doublecmd.sourceforge.io/site/eng/snapshots.php).

P.S. Excuse my curiosity, 2560x1600? Seriously? :) Useful information - ~940x180. Alt+PrtSc should work in Debian as well...

**Comment by Kolcha** [comment]
yes, looks like the same as #261 , didn't found it even looked for something similar before posting...

tried latest AppImage with version 1.1.0 alpha something (version is visible in window title), **bug still exists**:

![Screenshot_2022-03-21_20-54-08](https://user-images.githubusercontent.com/947647/159334631-75e86c12-9047-4581-b8b9-76043b472f43.png)

> P.S. Excuse my curiosity, 2560x1600? Seriously? :) Useful information - ~940x180. Alt+PrtSc should work in Debian as well...

2560x1600 for 14" screen :) (previously was 2560x1600 for 13.3" on old MacBook) Alt + PrtScn works, but why to care about file size?? this is even less 400k for such almost solid color image, even in PNG. uploading it takes moments. and also there is nothing "super secure" on these screenshots, but it may contain some useful information like version number (just a proof that version in the text is the same).

**Comment by Skif-off** [comment]
I meant width and height, not size :) In some cases, it's just not very inconvenient because too big but without much need (mobie/smart phone, netbook and etc.).

**Comment by Kolcha** [comment]
tested latest available nightly builds on Debian testing - issue seems to be gone. closing
